### ISSUE TITLE
Purpose of the project

### ISSUE THREAD

**Issue by ytrezq** [flinc/concealer#1]
Hello, if I understand correctly, the purpose of this project is to hide/obfuscate the source code of ruby files. Isn’t it ?

**Comment by fabrik42** [comment]
Hi,
the purpose of this project is to add a privacy layer around the values of an object.
You can implement your own privacy strategies to determine if a method is allowed to return its value or not. Further, you can implement your own fallback strategies to show something else instead.

A common use case would be:

``` ruby
# when logged in
user.concealed.email # => "hello@example.org"
# when logged out
user.concealed.name # => "Login to view email address"
```

It has nothing to do with the obfuscation of source code.

Cheers,
Christian
